### PR TITLE
Several updates

### PR DESCRIPTION
**Pull request by sebasmagri**
- Update requirements
- Update for django-browserid 0.8
- Style form widgets wrt #4

### CODE REVIEW

**Comment by nukeador** [comment]
Is django-browserid 0.8 working with mozbuzz?

Last time I checked we had to go back to 0.7 branch to make it work.

**Comment by sebasmagri** [comment]
Hi @nukeador.

You are right. However, I'll try to update mozbuzz to 0.8 and update the pull request.

Regards,

**Comment by sebasmagri** [comment]
@nukeador I've added some commits and as far as I tried it's working with django-browserid 0.8. Could you please check this out?

**Comment by sebasmagri** [comment]
Any updates?

**Comment by nukeador** [comment]
@YouWoTMA @felipelerena Please review this pull request.

**Comment by dvdbng** [comment]
Looks good, let me just test it locally (24-48 hours since I have to get back to England first) and I'll merge it.

**Comment by dvdbng** [comment]
Merged, works correctly but for some reason doesn't work if the SITE_URL has a tailing slash (I have updated the default settings in bcbccc0edc0b56de2d943bfd3974161df5dad691)

**Comment by nukeador** [comment]
Guys, production site is broken

https://www.mozilla-hispano.org/mozbuzz/accounts/login/?next=/mozbuzz/

I've just be informed about this by @bernimel

**Comment by dvdbng** [comment]
Yeah, sorry, I had the same problem locally when testing the pull request,
but i forgot to tell you to upgrade the server :)

**Pull request merged**
